L 05/22/2021 - 18:38:52: SourceMod error session started
L 05/22/2021 - 18:38:52: Info (map "vsh_roadfromnowhere_v2") (file "/home/frenzoid/TF2_FF2/tf/addons/sourcemod/logs/errors_20210522.log")
L 05/22/2021 - 18:38:52: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/22/2021 - 18:38:52: [SM] Blaming: sbpp_sleuth.smx
L 05/22/2021 - 18:38:52: [SM] Call stack trace:
L 05/22/2021 - 18:38:52: [SM]   [0] SQL_TQuery
L 05/22/2021 - 18:38:52: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/22/2021 - 18:38:52: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/22/2021 - 18:40:22: Error log file session closed.
L 05/22/2021 - 21:03:50: SourceMod error session started
L 05/22/2021 - 21:03:50: Info (map "vsh_crevice_b5") (file "/home/frenzoid/TF2_FF2/tf/addons/sourcemod/logs/errors_20210522.log")
L 05/22/2021 - 21:03:50: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/22/2021 - 21:03:50: [SM] Blaming: sbpp_sleuth.smx
L 05/22/2021 - 21:03:50: [SM] Call stack trace:
L 05/22/2021 - 21:03:50: [SM]   [0] SQL_TQuery
L 05/22/2021 - 21:03:50: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/22/2021 - 21:03:50: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/22/2021 - 21:04:26: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/22/2021 - 21:04:26: [SM] Blaming: sbpp_sleuth.smx
L 05/22/2021 - 21:04:26: [SM] Call stack trace:
L 05/22/2021 - 21:04:26: [SM]   [0] SQL_TQuery
L 05/22/2021 - 21:04:26: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/22/2021 - 21:04:27: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/22/2021 - 21:05:09: Error log file session closed.
L 05/22/2021 - 21:05:37: SourceMod error session started
L 05/22/2021 - 21:05:37: Info (map "vsh_intrusion_rc2") (file "/home/frenzoid/TF2_FF2/tf/addons/sourcemod/logs/errors_20210522.log")
L 05/22/2021 - 21:05:37: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/22/2021 - 21:05:37: [SM] Blaming: sbpp_sleuth.smx
L 05/22/2021 - 21:05:37: [SM] Call stack trace:
L 05/22/2021 - 21:05:37: [SM]   [0] SQL_TQuery
L 05/22/2021 - 21:05:37: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/22/2021 - 21:05:38: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/22/2021 - 21:06:00: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/22/2021 - 21:06:00: [SM] Blaming: sbpp_sleuth.smx
L 05/22/2021 - 21:06:00: [SM] Call stack trace:
L 05/22/2021 - 21:06:00: [SM]   [0] SQL_TQuery
L 05/22/2021 - 21:06:00: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/22/2021 - 21:06:00: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
