L 05/28/2021 - 19:01:27: SourceMod error session started
L 05/28/2021 - 19:01:27: Info (map "vsh_aquaticbase_b5") (file "/home/frenzoid/TF2_FF2/tf/addons/sourcemod/logs/errors_20210528.log")
L 05/28/2021 - 19:01:27: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/28/2021 - 19:01:27: [SM] Blaming: sbpp_sleuth.smx
L 05/28/2021 - 19:01:27: [SM] Call stack trace:
L 05/28/2021 - 19:01:27: [SM]   [0] SQL_TQuery
L 05/28/2021 - 19:01:27: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/28/2021 - 19:01:28: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/28/2021 - 19:06:45: Error log file session closed.
L 05/28/2021 - 19:07:27: SourceMod error session started
L 05/28/2021 - 19:07:27: Info (map "vsh_egyptyspot_reworked_b2b") (file "/home/frenzoid/TF2_FF2/tf/addons/sourcemod/logs/errors_20210528.log")
L 05/28/2021 - 19:07:27: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/28/2021 - 19:07:27: [SM] Blaming: sbpp_sleuth.smx
L 05/28/2021 - 19:07:27: [SM] Call stack trace:
L 05/28/2021 - 19:07:27: [SM]   [0] SQL_TQuery
L 05/28/2021 - 19:07:27: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/28/2021 - 19:07:27: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/28/2021 - 19:07:33: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/28/2021 - 19:07:33: [SM] Blaming: sbpp_sleuth.smx
L 05/28/2021 - 19:07:33: [SM] Call stack trace:
L 05/28/2021 - 19:07:33: [SM]   [0] SQL_TQuery
L 05/28/2021 - 19:07:33: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/28/2021 - 19:07:33: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/28/2021 - 19:08:57: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/28/2021 - 19:08:57: [SM] Blaming: sbpp_sleuth.smx
L 05/28/2021 - 19:08:57: [SM] Call stack trace:
L 05/28/2021 - 19:08:57: [SM]   [0] SQL_TQuery
L 05/28/2021 - 19:08:57: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/28/2021 - 19:08:57: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/28/2021 - 19:37:47: Error log file session closed.
L 05/28/2021 - 19:38:49: SourceMod error session started
L 05/28/2021 - 19:38:49: Info (map "vsh_nebula_rc1") (file "/home/frenzoid/TF2_FF2/tf/addons/sourcemod/logs/errors_20210528.log")
L 05/28/2021 - 19:38:49: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/28/2021 - 19:38:49: [SM] Blaming: sbpp_sleuth.smx
L 05/28/2021 - 19:38:49: [SM] Call stack trace:
L 05/28/2021 - 19:38:49: [SM]   [0] SQL_TQuery
L 05/28/2021 - 19:38:49: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/28/2021 - 19:38:49: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/28/2021 - 20:07:53: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/28/2021 - 20:07:53: [SM] Blaming: sbpp_sleuth.smx
L 05/28/2021 - 20:07:53: [SM] Call stack trace:
L 05/28/2021 - 20:07:53: [SM]   [0] SQL_TQuery
L 05/28/2021 - 20:07:53: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/28/2021 - 20:07:53: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/28/2021 - 20:09:14: Error log file session closed.
L 05/28/2021 - 20:09:55: SourceMod error session started
L 05/28/2021 - 20:09:55: Info (map "vsh_shipment_v1a") (file "/home/frenzoid/TF2_FF2/tf/addons/sourcemod/logs/errors_20210528.log")
L 05/28/2021 - 20:09:55: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/28/2021 - 20:09:55: [SM] Blaming: sbpp_sleuth.smx
L 05/28/2021 - 20:09:55: [SM] Call stack trace:
L 05/28/2021 - 20:09:55: [SM]   [0] SQL_TQuery
L 05/28/2021 - 20:09:55: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/28/2021 - 20:09:56: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/28/2021 - 20:16:58: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/28/2021 - 20:16:58: [SM] Blaming: sbpp_sleuth.smx
L 05/28/2021 - 20:16:58: [SM] Call stack trace:
L 05/28/2021 - 20:16:58: [SM]   [0] SQL_TQuery
L 05/28/2021 - 20:16:58: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/28/2021 - 20:16:59: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/28/2021 - 21:00:46: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/28/2021 - 21:00:46: [SM] Blaming: sbpp_sleuth.smx
L 05/28/2021 - 21:00:46: [SM] Call stack trace:
L 05/28/2021 - 21:00:46: [SM]   [0] SQL_TQuery
L 05/28/2021 - 21:00:46: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/28/2021 - 21:00:46: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/28/2021 - 21:01:25: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/28/2021 - 21:01:25: [SM] Blaming: sbpp_sleuth.smx
L 05/28/2021 - 21:01:25: [SM] Call stack trace:
L 05/28/2021 - 21:01:25: [SM]   [0] SQL_TQuery
L 05/28/2021 - 21:01:25: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/28/2021 - 21:01:25: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/28/2021 - 21:01:53: Error log file session closed.
L 05/28/2021 - 21:02:27: SourceMod error session started
L 05/28/2021 - 21:02:27: Info (map "vsh_tranquil_b5") (file "/home/frenzoid/TF2_FF2/tf/addons/sourcemod/logs/errors_20210528.log")
L 05/28/2021 - 21:02:27: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/28/2021 - 21:02:27: [SM] Blaming: sbpp_sleuth.smx
L 05/28/2021 - 21:02:27: [SM] Call stack trace:
L 05/28/2021 - 21:02:27: [SM]   [0] SQL_TQuery
L 05/28/2021 - 21:02:27: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/28/2021 - 21:02:27: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/28/2021 - 21:02:29: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/28/2021 - 21:02:29: [SM] Blaming: sbpp_sleuth.smx
L 05/28/2021 - 21:02:29: [SM] Call stack trace:
L 05/28/2021 - 21:02:29: [SM]   [0] SQL_TQuery
L 05/28/2021 - 21:02:29: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 05/28/2021 - 21:02:29: [sbpp_comms.smx] Connecting to database failed: [2003]: Can't connect to MySQL server on 'oldbox.cloud' (111)
L 05/31/2021 - 00:02:15: Error log file session closed.
